channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - perl
  - perl-app-cpanminus
  - perl-local-lib
  - python
  - samtools
  - snakemake
  - pyyaml
  - bamutil
  - trimmomatic
  - bismark
  - cutadapt
  - bedtools
